version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app
  backend:
    build: ./backend
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
